language: python
python:
    - "2.6"
    - "2.7"
    - "3.4"
env:
    - TOX_ENV=py26
    - TOX_ENV=py27
    - TOX_ENV=py34
    - TOX_ENV=flake8
before_install:
    - sudo apt-get update
    - sudo apt-get install -y libyaml-dev python-dev libffi-dev python-pip gnupg
install:
    - pip install tox
    - pip install -r requirements.txt
script:
    - tox -e $TOX_ENV
    - make functional-tests-once
